### PR TITLE
Restore license full text

### PR DESCRIPTION
**Pull request by pombredanne**
Somehow the text was truncated. 
This restores the text from https://www.gnu.org/licenses/agpl-3.0.txt

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by noahbenson** [comment]
Oh wow, thanks for catching this! I am rerunning the tests (which I'm pretty sure failed due to a timeout on data it downloads for the tests) and will accept when they pass.

**Comment by noahbenson** [comment]
I take that back; looks like one of my dependencies has some recently-deprecated code. Will accept when I figure it out.

**Comment by pombredanne** [comment]
> Oh wow, thanks for catching this!

Actually I was running a mostly routine set of scans mostly at random to catch new licenses with https://github.com/nexB/scancode-toolkit and yours came out as suspicious because it was both a large and a partial match to the full AGPL text. 

Glad it helps you to also spot some dependency issues!

**Comment by noahbenson** [comment]
Okay; seems that travis-ci recently had an update in which the version of pytest being used was changed. Anyway, I think it's all good now. Thanks again for catching this!

**Pull request merged**
